FROM ros:rolling

# setup environment
ENV LANG C.UTF-8

# install packages
RUN apt-get update && apt-get install -q -y --no-install-recommends \
    dirmngr \
    gnupg2 \
    git \
    wget \
    && rm -rf /var/lib/apt/lists/*


# installing universal_robot
RUN apt-get update && apt-get install -y ros-rolling-ur

# setup entrypoint
ENTRYPOINT [ "/bin/bash" ]