FROM universalrobots/ursim_cb3

# Install the URCap
COPY externalcontrol-1.0.5.urcap /urcaps/externalcontrol-1.0.5.jar

# Install pre-made programs
COPY programs ursim/programs

# command to 
#docker run --rm -it -e ROBOT_MODEL=UR3 -p 6080:6080 -p 5900:5900 universalrobots/ursim_cb3