FROM osrf/icra2023_ros2_gz_tutorial:tutorial_nvidia

# setup environment
ENV LANG C.UTF-8

# Copy the container_menu script into the container
COPY  container_menu.sh /root/container_menu.sh
RUN chmod +x /root/container_menu.sh


# Expose the necessary ports for Gazebo
EXPOSE 11345
EXPOSE 11311

# Luach into the terminal into /root directory
WORKDIR /root
CMD ["/bin/bash"]

# # Source ROS 2 setup file and workspace setup file, then run the launch file
# CMD /bin/bash -c "source /opt/ros/${ROS_DISTRO}/setup.bash && source /root/workspaces/ur_gazebo/install/setup.bash && ros2 launch ur_simulation_gazebo ur_sim_control.launch.py"