FROM ros:rolling-ros-core-jammy

# setup environment
ENV LANG C.UTF-8

# install packages
RUN apt-get update && apt-get install -q -y --no-install-recommends \
    dirmngr \
    gnupg2 \
    git \
    ros-humble-ur \
    && rm -rf /var/lib/apt/lists/*

# Expose the necessary ports for Gazebo
EXPOSE 11345
EXPOSE 11311

# Luach into the terminal into /root directory
WORKDIR /root
CMD ["/bin/bash"]

# # Source ROS 2 setup file and workspace setup file, then run the launch file
# CMD /bin/bash -c "source /opt/ros/${ROS_DISTRO}/setup.bash && source /root/workspaces/ur_gazebo/install/setup.bash && ros2 launch ur_simulation_gazebo ur_sim_control.launch.py"